OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

TAP_DANCE_ENABLE = yes

# OS_DETECTION_DEBUG_ENABLE = yes

ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE = yes

ifeq ($(strip $(OS_DETECTION_DEBUG_ENABLE)), yes)	
	CONSOLE_ENABLE = yes

	MOUSE_ENABLE = no
	MOUSEKEY_ENABLE = no
	JOYSTICK_ENABLE = no
	MIDI_ENABLE = no
	STENO_ENABLE = no
	VIRTSER_ENABLE = no
	EXTRAKEY_ENABLE = no
	DIGITIZER_ENABLE = no
	NKRO_ENABLE = no  
endif